### POST Start Process
POST http://127.0.0.1:8081/rest/process/start
Content-Type: application/json

{
  "name": "Peter Heinemann",
  "email": "peter.heinemann@miragon.io",
  "dateFrom": "2025-01-01",
  "dateTo": "2025-02-01",
  "cost": 2000,
  "destination": "Hamburg"
}

### GET Form Data
@taskId = 6755399517262613
GET http://127.0.0.1:8081/rest/task/{{taskId}}/load